version: '3.8'

services:
  dotnet:
    depends_on:
        - rabbitmq
    image: background-task-queue
    container_name: background-task-queue
    tty: true
    volumes:
      - ./:/app
    build:
      context: ./
      dockerfile: background-task-queue.CORE/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
       - rabbitmq_net

  rabbitmq:           
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"     # Porta de comunicação (RabbitMQ)
      - "15672:15672"   # Porta do painel web (RabbitMQ Management)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge